### ISSUE TITLE
 How to use this simulator tool

### ISSUE THREAD

**Issue by willann** [aligungr/UERANSIM#68] opened 2020-07-30 05:18 UTC
Thanks to the author, I compiled the code.When I use this tool, there is a OutOfMemoryError

# java -jar ueransim-1.0.8.jar
WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration"
]
Type event:
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61)
        at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:348)
        at tr.havelsan.ueransim.sctp.SctpClient.receiverLoop(SctpClient.java:87)
        at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:50)

**Comment by tim-ywliu** [comment] 2020-07-30 08:30
I just created a PR #69 that can fix this issue.

**Comment by aligungr** [comment] 2020-07-30 18:34
@tim-ywliu Thanks for the PR. Now merged to master

**Comment by willann** [comment] 2020-07-31 03:12
> I just created a PR #69 that can fix this issue.

Thank you for your help, but it did not solve the problem,This problem still occurs,Attach app.log
[app.log](https://github.com/aligungr/ue-ran-sim/files/5004863/app.log)

**Comment by tim-ywliu** [comment] 2020-07-31 06:50
@willann 

How about trying to decrease RECEIVER_BUFFER_SIZE to 6400?

**Comment by willann** [comment] 2020-07-31 07:37
> @willann
> 
> How about trying to decrease RECEIVER_BUFFER_SIZE to 6400?


I have reduced this value，but it didn't work.By the way,should this tool be placed in a different VM from 5gc? 
I put 5gc and tools in the same machine

here is gnb.yaml 

gnbId: 1
gnbPlmn:
  mcc: 001
  mnc: 01
amfConfigs:
  - guami:
      mcc: 001
      mnc: 01
      amfRegionId:
        hex: '2a'
      amfSetId:
        hex: '5580'
      amfPointer:
        hex: 'a8'
    host: 192.168.12.183
    port: 38412
    isMocked: false
    mockingFile: mockedAmf.yaml

This host is an ip address to be connected to the real gnb

**Comment by tim-ywliu** [comment] 2020-07-31 07:43
@willann 

This tool is ue-gnb emulator. Why do you add a real gnb to connect?

You can refer to [https://github.com/aligungr/ue-ran-sim/issues/71#issuecomment-666942646](https://github.com/aligungr/ue-ran-sim/issues/71#issuecomment-666942646) to follow the settings.

**Comment by willann** [comment] 2020-07-31 09:34
@tim-ywliu 
thanks for you help
I want to simulate the real environment and create a separate network card to connect to the gnb.
‘192.168.12.183’ Is the  ip address of the local network card
I changed the host address to 127.0.0.1 in gnb.yaml，There will be a connection refused.

here is log
WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration"
]
Type event:
java.lang.RuntimeException: java.net.ConnectException: Connection refused
        at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:52)
Caused by: java.net.ConnectException: Connection refused
        at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect0(Native Method)
        at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect(SctpNet.java:68)
        at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:378)
        at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:445)
        at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:226)
        at tr.havelsan.ueransim.sctp.SctpClient.start(SctpClient.java:63)
        at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:49)

**Comment by willann** [comment] 2020-07-31 10:18
@tim-ywliu 
when I modify the host address of the gnb.yaml to a non-existent address, such as 192.168.0.0, looks like it works

WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration"
]
Type event:
initial-registration
Event pushed.
Type event:
java.lang.NullPointerException
        at tr.havelsan.ueransim.sctp.SctpClient.send(SctpClient.java:75)
        at tr.havelsan.ueransim.api.gnb.GNodeB.sendToNetworkUeAssociated(GNodeB.java:109)
        at tr.havelsan.ueransim.api.gnb.GnbNasTransport.receiveUplinkNasTransport(GnbNasTransport.java:72)
        at tr.havelsan.ueransim.api.gnb.GNodeB.cycle(GNodeB.java:180)
        at tr.havelsan.ueransim.core.threads.NodeLooperThread.run(NodeLooperThread.java:50)

**Comment by aligungr** [comment] 2020-07-31 14:31
@willann The IP address in the gnb.yaml file is the IP of related AMF, but not gNB.

Also if I understand you correctly, This tool is both UE and gNB emulator and they cannot be seperated each other. I mean currently the tool cannot be used as UE only or gNB only.

**Comment by willann** [comment] 2020-08-01 02:27
@aligungr 
Yes,I know what you mean.The ip address I modified is the address of AMF  in the gnb.yaml file,however caused the OutOfMemoryError.
Is it because I use a separate network card？How many gnb or ue can be simulated at the same time by this tool.

**Comment by aligungr** [comment] 2020-08-01 02:52
@willann Seperate network card should not cause OutOfMemoryError. This error is all about Java virtual machine. My opinion is that, are you really sure that you decreased the RECEIVER_BUFFER_SIZE? (Printing out the value may be useful to see the value at runtime.)


If you certainly decreased the value, you can try executing the java program with -XX:MaxRAMFraction=1 option. If it still gives the error, you may want to share wireshark logs to see if some SCTP connection bombarding the app. But as I said before, I suspect the buffer size value.

--

Theorotically this tool can simulate unlimited number of ue and gnbs as long as your computer and environment resist. There is no limitation caused by the application itself.

**Closed** 2020-08-06 22:07 UTC
